"""Init models

Revision ID: 324d438c9e5f
Revises:
Create Date: 2026-02-11 13:34:59.605588+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "324d438c9e5f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment_delivery_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("form_title", sa.Text(), nullable=True),
        sa.Column("form_public_url", sa.Text(), nullable=True),
        sa.Column("comment_id", sa.UUID(), nullable=False),
        sa.Column("comment_title", sa.Text(), nullable=True),
        sa.Column("comment_text", sa.Text(), nullable=True),
        sa.Column("comment_author_first_name", sa.String(length=255), nullable=True),
        sa.Column("comment_author_last_name", sa.String(length=255), nullable=True),
        sa.Column("comment_author_phone", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment_delivery_log")
    # ### end Alembic commands ###
